package io.helidon.mp.mybatisplus.service;

import io.helidon.mp.mybatisplus.entity.Employee;
import io.helidon.mp.mybatisplus.entity.EmployeeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.SqlSession;

import java.util.List;

public interface EmployeeService {

    void setEmployeeMapper(SqlSession sqlSession);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table EMPLOYEE
     *
     * @mbg.generated Wed Apr 24 11:27:25 CST 2019
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table EMPLOYEE
     *
     * @mbg.generated Wed Apr 24 11:27:25 CST 2019
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table EMPLOYEE
     *
     * @mbg.generated Wed Apr 24 11:27:25 CST 2019
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table EMPLOYEE
     *
     * @mbg.generated Wed Apr 24 11:27:25 CST 2019
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table EMPLOYEE
     *
     * @mbg.generated Wed Apr 24 11:27:25 CST 2019
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table EMPLOYEE
     *
     * @mbg.generated Wed Apr 24 11:27:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table EMPLOYEE
     *
     * @mbg.generated Wed Apr 24 11:27:25 CST 2019
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);
}