package io.helidon.mp.mybatisplus.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import io.helidon.mp.mybatisplus.entity.Employee;
import io.helidon.mp.mybatisplus.entity.EmployeeExample;

@org.mybatis.cdi.Mapper
public interface EmployeeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Wed Apr 24 11:27:25 CST 2019
	 */
	long countByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Wed Apr 24 11:27:25 CST 2019
	 */
	int deleteByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Wed Apr 24 11:27:25 CST 2019
	 */
	int insert(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Wed Apr 24 11:27:25 CST 2019
	 */
	int insertSelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Wed Apr 24 11:27:25 CST 2019
	 */
	List<Employee> selectByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Wed Apr 24 11:27:25 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Wed Apr 24 11:27:25 CST 2019
	 */
	int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);
}
